from django.urls import path
from .views import *

urlpatterns = [
    path('vehicles/', VehicleListView.as_view(), name='vehicle-list'),
    path('vehicles/<int:pk>/', VehicleView.as_view(), name='vehicle-detail'),
    path('vehicles/utility/', UtilityVehicleListCreateView.as_view(), name='utility-vehicle-list-create'),
    path('vehicles/utility/<int:pk>/', UtilityVehicleRetrieveUpdateDestroyView.as_view(), name='utility-vehicle-detail'),
    path('vehicles/tourist/', TouristVehicleListCreateView.as_view(), name='tourist-vehicle-list-create'),
    path('vehicles/tourist/<int:pk>/', TouristVehicleRetrieveUpdateDestroyView.as_view(), name='tourist-vehicle-detail'),
    path('vehicles/luxury/', LuxuryVehicleListCreateView.as_view(), name='luxury-vehicle-list-create'),
    path('vehicles/luxury/<int:pk>/', LuxuryVehicleRetrieveUpdateDestroyView.as_view(), name='luxury-vehicle-detail'),
    path('drivers/', DriverListCreateView.as_view(), name='driver-list-create'),
    path('drivers/<int:pk>/', DriverRetrieveUpdateDestroyView.as_view(), name='driver-detail'),
    path('rental-agencies/', RentalAgencyListCreateView.as_view(), name='rental-agency-list-create'),
    path('rental-agencies/<int:pk>/', RentalAgencyRetrieveUpdateDestroyView.as_view(), name='rental-agency-detail'),
    path('rentals/', RentalListCreateView.as_view(), name='rental-list-create'),
    path('rentals/<int:pk>/', RentalRetrieveUpdateDestroyView.as_view(), name='rental-detail'),
    path('payments/', PaymentDetailView.as_view(), name='payment-list-create'),
    path('payments/<int:pk>/', PaymentDetailView.as_view(), name='payment-detail'),
    path('insurance/', InsuranceListView.as_view(), name='insurance-list-create'),
    path('insurance/<int:pk>/', InsuranceDetailView.as_view(), name='insurance-detail'),
    path('technical-inspections/', TechnicalInspectionListView.as_view(), name='technical-inspection-list-create'),
    path('technical-inspections/<int:pk>/', TechnicalInspectionDetailView.as_view(), name='technical-inspection-detail'),
    path('vehicle-status/', VehicleStatusListView.as_view(), name='vehicle-status-list-create'),
    path('vehicle-status/<int:pk>/', VehicleStatusDetailView.as_view(), name='vehicle-status-detail'),
    path('location-agency/', LocationAgencyListCreateView.as_view(), name='location-agency-list-create'),
    path('location-agency/<int:pk>/', LocationAgencyDetailView.as_view(), name='location-agency-detail'),
    path('incidents/', IncidentListCreateView.as_view(), name='incident-list-create'),
    path('incidents/<int:pk>/', IncidentDetailView.as_view(), name='incident-detail'),
    path('quarterly-statistics/', QuarterlyStatisticsListCreateView.as_view(), name='quarterly-statistics-list-create'),
    path('quarterly-statistics/<int:pk>/', QuarterlyStatisticsDetailView.as_view(), name='quarterly-statistics-detail'),
    path('reminders/', ReminderListCreateView.as_view(), name='reminder-list-create'),
    path('reminders/<int:pk>/', ReminderDetailView.as_view(), name='reminder-detail'),
]
